/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Code.Patient;
import static Code.Patient.Patient_List;
import Code.Person;
import Code.Person_Directory;
import Code.VitalSigns;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saich
 */
public class Overview extends javax.swing.JPanel {

    /**
     * Creates new form Overview
     */
boolean seen = false;
Person_Directory P_d = new Person_Directory();
    public Overview(Person_Directory P_d) {
        initComponents();
        this.P_d = P_d;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTxtCommSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldviewPhone = new javax.swing.JTextField();
        jTextviewCommunityid = new javax.swing.JTextField();
        jTextviewId = new javax.swing.JTextField();
        jTextviewName = new javax.swing.JTextField();
        jTextviewDob = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 255));
        setForeground(new java.awt.Color(51, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "DOB", "ID", "Community_Id", "Phone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search All Communities");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("                                         Pateints with Abnomal Conditions");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Community id: ");

        jLabel3.setText("Name");

        jLabel4.setText("Dob");

        jLabel5.setText("Id");

        jLabel6.setText("Community_iD");

        jLabel7.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextviewName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(48, 48, 48)
                                        .addComponent(jTxtCommSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton2)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldviewPhone))
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonView)
                                        .addGap(66, 66, 66))))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addComponent(jTextviewId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(jTextviewCommunityid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCommSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jButton2))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonView))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldviewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextviewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextviewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jTextviewCommunityid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextviewDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


     // ArrayList <Patient> ps = Patient.Patient_List;
     // System.out.println(ps.size());


for (Person p :Person_Directory.person_list){
  
if (p.isIsPatient() == true){
  
  Patient pat = new Patient();
pat.setDOB(p.getDOB());
  pat.setId(p.getId());
  pat.setCommunity_Id(p.getCommunity_Id());
  pat.setName(p.getName());
pat.setPhone_number(p.getPhone_number());
  //pat.setVs(p.getVs());
  pat.setVitalSigns_List(p.getVitalSigns_List());
 
  Patient.Patient_List.add(pat);}

}



//populateTable();

System.out.println(Patient.Patient_List.size());

for (Patient abs : Patient.Patient_List){

// System.out.println(Patient.Patient_List.size());

if (abs.getVitalSigns_List().size() > 0 ){
 VitalSigns vs = abs.getVitalSigns_List().get(abs.getVitalSigns_List().size()-1);

 //for (VitalSigns vs : abs.getVitalSigns_List()){

  if (vs.getBlood_oxygen() <= 80){
      Patient.AbnoRMAL_patientsList.add(abs);


}

 else if (vs.getSystolic_pressure()>=150 || vs.getSystolic_pressure()<= 80){
Patient.AbnoRMAL_patientsList.add(abs);
}

else if (vs.getTemperature()>=100 || vs.getTemperature() < 80){
Patient.AbnoRMAL_patientsList.add(abs);
}



//}



}

}
populateTable();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    if ( ! jTxtCommSearch.getText().isEmpty()){
     for (Patient ps : Patient.AbnoRMAL_patientsList){
          if (ps.getCommunity_Id() ==  Integer.parseInt(jTxtCommSearch.getText())){
               Patient.SearchList.add(ps);
      

}
   


}
populateTablesearch();}
else {

      JOptionPane.showMessageDialog(null, " Please type a valid value ");  }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:

int selected_row = jTable1.getSelectedRow();
if (selected_row<0){
JOptionPane.showMessageDialog(this, "Please select a row to delete");
return;

}
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
Person selectedPerson = (Person)model.getValueAt(selected_row, 0);
int id = selectedPerson.getId();
for (Patient p :Patient.AbnoRMAL_patientsList){
  
if (p.getId()==id){
Patient.AbnoRMAL_patientsList.remove(p);}

}
JOptionPane.showMessageDialog(this, "Values deleted");
populateTable();


    
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:

int row1 = jTable1.getSelectedRow();
int col1 =  jTable1.getSelectedColumn();
    

 if (row1 >= 0){
    

    jTextFieldviewPhone.setText(jTable1.getValueAt(row1,4).toString());
    jTextviewCommunityid.setText(jTable1.getValueAt(row1,3).toString());
    jTextviewDob.setText(jTable1.getValueAt(row1,1).toString());
    jTextviewId.setText(jTable1.getValueAt(row1,2).toString());
    jTextviewName.setText(jTable1.getValueAt(row1,0).toString());
    


   
   

   

}
else {
JOptionPane.showMessageDialog(this, "Please select a row");
   
}






    }//GEN-LAST:event_jButtonViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldviewPhone;
    private javax.swing.JTextField jTextviewCommunityid;
    private javax.swing.JTextField jTextviewDob;
    private javax.swing.JTextField jTextviewId;
    private javax.swing.JTextField jTextviewName;
    private javax.swing.JTextField jTxtCommSearch;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
 for (Patient p : Patient.AbnoRMAL_patientsList){
 
Object [] row =new Object[5];
row[0]= p;
//row[1]= p.getAge();
row[1]= p.getDOB();
row[2]= p.getId();
row[3]= p.getCommunity_Id();
row[4]= p.getPhone_number();

model.addRow(row);

    }








    }

    private void populateTablesearch() {
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);


for (Patient p : Patient.SearchList){
 
Object [] row =new Object[5];
row[0]= p;
//row[1]= p.getAge();
row[1]= p.getDOB();
row[2]= p.getId();
row[3]= p.getCommunity_Id();
row[4]= p.getPhone_number();

model.addRow(row);







    }

}
}
